### ISSUE TITLE
"AttributeError: partially initilized module 'fiona' has no attribute '_loading'" in notebook from docker container

### ISSUE THREAD

**Issue by btcpcs** [anitagraser/EDA-protocol-movement-data#2]
![error running notebook from docker container](https://user-images.githubusercontent.com/69687675/133351287-6487d8d7-5df9-4492-ac59-cb18860182b1.PNG)

Great work on this notebook. I successfully built the container but I see the attached error when running the notebook. Any ideas?

Thanks

**Comment by anitagraser** [comment]
I haven't seen that error before so I'll have to investigate.

**Comment by anitagraser** [comment]
In the meantime, here's a copy of the image I built: [eda-protocol-movement-data-1.0.tar.gz](https://www.dropbox.com/s/8ujak1pxkbpufz5/eda-protocol-movement-data-1.0.tar.gz?dl=0)

**Comment by mataruev** [comment]
Hello! Thank you for your great works! I have the same error. And in repo https://github.com/MBennGit/mobilitydb-sqlalchemy-notebooks the same.

**Comment by anitagraser** [comment]
Seems like BASE_CONTAINER=jupyter/minimal-notebook now installs Python 3.9 instead of 3.7 and that causes issues.

**Comment by anitagraser** [comment]
@btcpcs please try with the new docker file.

**Comment by btcpcs** [comment]
@anitagraser - thank your vey much. This resolved the issue.

**Comment by anitagraser** [comment]
This error is potentially related to https://github.com/geopandas/geopandas/issues/2123#issuecomment-927178129
