### ISSUE TITLE
The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by miladad8** [anitagraser/EDA-protocol-movement-data#5]
hi, when i try to run this line 'df['SOG'].hist(bins=100, figsize=(15,3))' i got kernel error and the output display this ''<AxesSubplot:>'' and doesn't print histogram

**Comment by anitagraser** [comment]
Welcome miladad8. Can you elaborate a little more about how and when this error happens? Are you using the Docker image or have you set up the Python environment using conda? Do other plots work?

**Comment by miladad8** [comment]
thx for your response.the problem wasn't specific to this file and matplotlib had an issue with ploting with conda environment.i fixed that but now  when i try to run ''df = df[df.SOG>0]'' i get an error :
 TypeError: '>' not supported between instances of 'str' and 'int'
i'm using jupyter notebook.i think it's because of type differences between dataframe column (string) and 0(int).but i don't know how to fix it..sorry for interrupting.i'm new to python

**Comment by anitagraser** [comment]
Are you using the file I shared or are you using your own data?

You could try:

```
df['SOG'] = pd.to_numeric(df['SOG'])  # potentially with errors='ignore' (https://pandas.pydata.org/docs/reference/api/pandas.to_numeric.html)
df = df[df.SOG>0]
```

**Comment by miladad8** [comment]
still get the str and int error.i have a standard AIS CSV file with SOG column

**Comment by anitagraser** [comment]
I'm not sure where that input file is coming from but these are note valid numeric values:

![image](https://user-images.githubusercontent.com/590385/143932498-30e444b5-ae75-48d8-adf0-ccf0cd851a01.png)

**Comment by miladad8** [comment]
this is the AIS data that i have downloaded:
[](https://www.fisheries.noaa.gov/inport/item/53161)
the main CSV file is really huge and i just broke it down into several files and i didn't make any changes to the raw data.anyway thank you for your time.i will work on it to find a way.
